// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9gnNPUBg_JYbmo-aBYh8ljKQVn1BGYE',
    appId: '1:966133665205:web:a7c7729831b4139b551dfc',
    messagingSenderId: '966133665205',
    projectId: 'smart-study-planner-8b6c6',
    authDomain: 'smart-study-planner-8b6c6.firebaseapp.com',
    storageBucket: 'smart-study-planner-8b6c6.firebasestorage.app',
    measurementId: 'G-3FR5WMSDWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3fhiTg_lqW_OhYzrFA2uqPWffdilUfw',
    appId: '1:966133665205:android:f36c2de4362e885d551dfc',
    messagingSenderId: '966133665205',
    projectId: 'smart-study-planner-8b6c6',
    storageBucket: 'smart-study-planner-8b6c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-rqrdZPwj4puAM2NbN9kKchjSCe3u3ME',
    appId: '1:966133665205:ios:aff9ef7a6784fa6a551dfc',
    messagingSenderId: '966133665205',
    projectId: 'smart-study-planner-8b6c6',
    storageBucket: 'smart-study-planner-8b6c6.firebasestorage.app',
    iosClientId: '966133665205-9dfbcvf3ngmknqecfv8l13oi2n8qj797.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStudyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-rqrdZPwj4puAM2NbN9kKchjSCe3u3ME',
    appId: '1:966133665205:ios:aff9ef7a6784fa6a551dfc',
    messagingSenderId: '966133665205',
    projectId: 'smart-study-planner-8b6c6',
    storageBucket: 'smart-study-planner-8b6c6.firebasestorage.app',
    iosClientId: '966133665205-9dfbcvf3ngmknqecfv8l13oi2n8qj797.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStudyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_9gnNPUBg_JYbmo-aBYh8ljKQVn1BGYE',
    appId: '1:966133665205:web:55dbf1c2c4c68c37551dfc',
    messagingSenderId: '966133665205',
    projectId: 'smart-study-planner-8b6c6',
    authDomain: 'smart-study-planner-8b6c6.firebaseapp.com',
    storageBucket: 'smart-study-planner-8b6c6.firebasestorage.app',
    measurementId: 'G-GGPT0PWVY3',
  );

}